spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
app:
  cors:
    paths: ["/**"]
    allowed-methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
    allowed-headers: [Authorization, Content-Type, Accept-Language, X-Request-Id]
    exposed-headers: [X-Request-Id, Content-Disposition]
    allow-credentials: true
    max-age: 3600
  cards:
    pan-hmac-secret: ${CARDS_PAN_HMAC_SECRET:change-me}